version: '3'
services:
  web:
    build:
      context: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - ./zookeeper:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_MESSAGE_MAX_BYTES=25000000
    volumes:
      - ./kafka:/var/lib/kafka/data
    depends_on:
      - zookeeper

  video-conversion:
    build:
      context: ./video
    volumes:
      - ./video:/app
    depends_on:
      - kafka

volumes:
  kafka:
  zookeeper:
  web:
  video:
