version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "video-topic:1:1"

  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: "bash -c 'until echo Waiting for Kafka to be ready... && nc -zv kafka 9092; do sleep 1; done && kafka-topics --create --topic video-topic --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092'"

  web:
    build:
      context: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - kafka

  video-conversion:
    build:
      context: ./video
    volumes:
      - ./video:/app
      - /app/node_modules
    depends_on:
      - kafka

  minio:
    image: minio/minio
    command: server --console-address ":9090" /data
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
     - minio-data:/data
    env_file: .env
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: /bin/sh
    command: >
      -c "
      mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb minio/input-bucket;
      mc mb minio/output-bucket;
      "

volumes:
  web:
  video:
  minio-data:
